version: "3.8"
services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/lyrebird
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lyrebird
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
